server {
  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    # Si un fichier ou un dossier n'est pas trouvé, on renvoie sur l'index.html
    try_files $uri $uri/ /index.html;
  }
}