global:
  scrape_interval: 5s # Fréquence de lecture des données

scrape_configs:
  - job_name: 'backend-collector'
    static_configs:
      - targets: ['backend:3000'] # On utilise le nom du service Docker