sonar.projectKey=Croco1609_collectorPerso
sonar.organization=croco1609-github

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusion (pour ne pas analyser les bibliothèques externes)
sonar.exclusions=**/node_modules/**, **/dist/**