name: CI Collector Shop

on: [push, pull_request]

jobs:
  test-and-audit:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DB_USER_CI }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD_CI }}
          POSTGRES_DB: ${{ secrets.DB_NAME_CI }}
        ports:
          - 5433:5432

    steps:
      - uses: actions/checkout@v3

      - name: Installation Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installation dépendances
        run: npm install

      - name: Audit de sécurité (DevSecOps)
        run: npm audit --audit-level=critical

      - name: Exécution des tests
        run: npm test
        env:
          DB_USER: ${{ secrets.DB_USER_CI }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_CI }}
          DB_HOST: 127.0.0.1
          DB_PORT: 5433
          DB_NAME: ${{ secrets.DB_NAME_CI }}